server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /u/ritz {
    return 301 /u/lmbrendle/;
  }

  location = /u/ritz/ {
    return 301 /u/lmbrendle/;
  }

  location /u/ {
    try_files $uri $uri/ /u/index.html;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
